### ISSUE TITLE
Tests fail after 2021-06-01

### ISSUE THREAD

**Issue by bmwiedemann** [aws-cloudformation/cfn-lint#1779]
See #1705 . It was not really fixed for good with #1777

**Comment by PatMyron** [comment]
https://github.com/aws-cloudformation/cfn-python-lint/issues/1705#issuecomment-699139633

**Comment by bmwiedemann** [comment]
I think, what the test should be testing is that python2.7 is not deprecated in 2020 and that python2.7 is deprecated in 2022 - independent of when the test is run.

> so far in advance

"far" is relative, because distributions like our openSUSE take their time to update code, so #1777 has not arrived there yet.

so far I thought, 15y is far enough.

**Comment by PatMyron** [comment]
> distributions like our openSUSE take their time to update code, so #1777 has not arrived there yet

[`cfn-lint` bundles lots of static data that gets outdated fairly quickly](https://github.com/aws-cloudformation/cfn-python-lint/pull/1792), so this test would be far from the main issue if distributions are that out of date

If https://software.opensuse.org/package/python-cfn-lint is correct that the latest version is [`v0.21.4`](https://github.com/aws-cloudformation/cfn-python-lint/releases/tag/v0.21.4) from May 2019, that lag is a problem by itself since what constitutes a valid CloudFormation template has changed quite a bit since then

**Comment by bmwiedemann** [comment]
We have cfn-python-lint-0.37.1.tar.gz from 2020-10-06

**Comment by PatMyron** [comment]
mitigated in https://github.com/aws-cloudformation/cfn-lint/pull/2029, next instance will be `python2.7` later this year:

https://github.com/aws-cloudformation/cfn-lint/blob/04297c1072015bb40e950bf935596cc742246fe8/src/cfnlint/data/AdditionalSpecs/LmbdRuntimeLifecycle.json#L47-L51

**Comment by yan12125** [comment]
Time's up for `python2.7` :)
An approach similar to #2029 makes tests pass. I'm not sure if it's correct, though.
```bash
sed -i 's#Runtime: python2\.7#Runtime: python3.8#' test/fixtures/templates/quickstart/{cis_benchmark,openshift}.yaml
```

**Comment by yan12125** [comment]
A similar issue surfaced again on 2021-09-30. The warning

> EOL runtime (python2.7) specified. Runtime is EOL since 2021-07-15 and updating will be disabled at 2021-09-30. Please consider updating to python3.8

becomes the error

> Deprecated runtime (python2.7) specified. Updating disabled since 2021-09-30. Please consider updating to python3.8

and thus tests fail.

A example log: https://reproducible.archlinux.org/api/v0/builds/168502/log
