### ISSUE TITLE
US-East-1 cloudspecs are missing attributes

### ISSUE THREAD

**Issue by Alex-Dettinger** [aws-cloudformation/cfn-lint#2343]
*cfn-lint version: 0.63.1*

*Description of issue.*
The cloud specs for us-east-1 in the latest update are missing Endpoint.Address & Endpoint.port for the DB Cluster. See https://github.com/aws-cloudformation/cfn-lint/pull/2335/files#diff-a5a6f378b19287fd419ef6c9edf44d4493163add0a727420af026573a02f165aR127103
These missing properties break our automated scripts that use cfn-lint

**Comment by kddejong** [comment]
I'll probably patch the specs and send a new release out shortly.

Working with some internal teams to understand why it got dropped.

**Comment by PatMyron** [comment]
previous compound attribute issues: https://github.com/aws-cloudformation/cfn-lint/issues/986, https://github.com/aws-cloudformation/cfn-lint/issues/2058

> Working with some internal teams to understand why it got dropped

First guess was a general compound attribute since compound attributes are currently rare (~71/1580 attributes), but doesn't look like they all got dropped, something specific to [`AWS::RDS::DBCluster`](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-rds-dbcluster.html)..

**Comment by kddejong** [comment]
Fixed the current issue but we may need to think of some ways to handle this going forward.
