### ISSUE TITLE
E0002 Error on yaml template

### ISSUE THREAD

**Issue by R00T88** [aws-cloudformation/cfn-lint#2383]
### CloudFormation Lint Version

0.65

### What operating system are you using?

Windows

### Describe the bug

[cfn-lint] E0002: Unknown exception while processing rule I3013: expected string or bytes-like object

on this row

AWSTemplateFormatVersion: '2010-09-09'

### Expected behavior

no error should be displayed

### Reproduction template

AWSTemplateFormatVersion: "2010-09-09"

**Comment by kddejong** [comment]
The placement of that error is generic because the rule failed.

Ideally if you could provide an example resource it would greatly help.  This rule checks these resources and properties:
Resource Type: `AWS::Kinesis::Stream` Attribute: `RetentionPeriodHours`
Resource Type: `AWS::SQS::Queue`  Attribute: `MessageRetentionPeriod`
Resource Type: `AWS::DocDB::DBCluster` Attribute: `BackupRetentionPeriod`
Resource Type: `AWS::Synthetics::Canary` Attribute: `SuccessRetentionPeriod`
Resource Type: `AWS::Synthetics::Canary` Attribute: `FailureRetentionPeriod`
Resource Type: `AWS::Redshift::Cluster` Attribute: `AutomatedSnapshotRetentionPeriod`
Resource Type: `AWS::RDS::DBInstance` Attribute: `BackupRetentionPeriod`
Resource Type: `AWS::RDS::DBCluster` Attribute: `BackupRetentionPeriod`

**Comment by R00T88** [comment]
@kddejong 

i use BackupRetentionPeriod on AWS::RDS::DBInstance

DBSAURORACLS001: # RDS Aurora Cluster
    Properties:
      BacktrackWindow: 259200
      BackupRetentionPeriod: 3
      CopyTagsToSnapshot: True
      DBClusterIdentifier: !Sub
          - 'ssc-rds-${OpCo}-${Dtap}-${Application}-${AppEnvCode}'
          - OpCo: !Ref OpCo
            Dtap: !Ref Dtap
            Application: !Ref Application
            AppEnvCode: !Ref AppEnvCode
      DBClusterParameterGroupName: !Ref 'DBSAURORACPG001'
      DBSubnetGroupName: !Ref 'DBSAURORASBT001'
      EnableCloudwatchLogsExports:
        - audit
        - general
        - slowquery
        - error
      Engine: !FindInMap [RdsEngineTypeMap, !Ref "AWS::Region", DBSAURORACLS001]
      EngineMode: provisioned
      EngineVersion: !FindInMap [RdsEngineVersionTypeMap, !Ref "AWS::Region", DBSAURORACLS001]
      MasterUserPassword: !If
        - UseDbSnapshot
        - !Ref 'AWS::NoValue'
        - !Ref 'MasterUserPassword'
      MasterUsername: !If
        - UseDbSnapshot
        - !Ref 'AWS::NoValue'
        - !Ref 'MasterUserName'
      SnapshotIdentifier: !If
        - UseDbSnapshot
        - !Ref 'SnapshotIdentifier'
        - !Ref 'AWS::NoValue'
      PreferredBackupWindow: "00:00-01:00"
      PreferredMaintenanceWindow: "sun:02:00-sun:04:00"
      StorageEncrypted: True
      Tags:
        - Key: Name
          Value: !Sub
            - 'ssc-rds-${OpCo}-${Dtap}-${Application}-${AppEnvCode}'
            - OpCo: !Ref OpCo
              Dtap: !Ref Dtap
              Application: !Ref Application
              AppEnvCode: !Ref AppEnvCode
        - Key: OpCo
          Value: !Ref OpCo
        - Key: Dtap
          Value: !Ref 'Dtap'
        - Key: Owner
          Value: !Ref 'Owner'
        - Key: Creator
          Value: !Ref 'Creator'
        - Key: Application
          Value: !Ref 'Application'
        - Key: Description
          Value: Digital Assessment MySql Aurora RDS
        - Key: Ec2ctl
          Value: n/a
        - Key: EnvCode
          Value: !Ref 'EnvCode'
        - Key: AppCodeExclude
          Value: True
      VpcSecurityGroupIds:
        - !Ref 'DBSAURORASG001'
    Type: AWS::RDS::DBCluster
