### ISSUE TITLE
Many AppStream instance type missing

### ISSUE THREAD

**Issue by jbellavance34** [aws-cloudformation/cfn-lint#2534]
The list of appstream instances allowed values type is missing some instance type.

Reference in the cfn-lint code : 
https://github.com/aws-cloudformation/cfn-lint/blob/63392195f54dc31177215657020907bdeb0d703d/src/cfnlint/data/ExtendedSpecs/ca-central-1/05_pricing_property_values.json#L984

AWS list of available instance type : https://docs.aws.amazon.com/appstream2/latest/APIReference/API_CreateFleet.html#AppStream2-CreateFleet-request-InstanceType 

Please update the list with the one provided by AWS.

**Comment by kddejong** [comment]
This list is based on pricing data as found in this script https://github.com/aws-cloudformation/cfn-lint/blob/main/scripts/update_specs_from_pricing.py#L243

When comparing `us-east-1` to that list the only one that is missing is `stream.graphics-desktop.2xlarge`

ca-central-1 has a bigger discrepancy but that is because, as far as I can tell, the z1d instances aren't available in ca-central-1.
```
stream.memory.z1d.large
stream.memory.z1d.xlarge
stream.memory.z1d.2xlarge
stream.memory.z1d.3xlarge
stream.memory.z1d.6xlarge
stream.memory.z1d.12xlarge
stream.graphics-desktop.2xlarge
```

**Comment by jbellavance34** [comment]
Thank you for the quick response.

I think that the update script would do the job.
