### ISSUE TITLE
TopicARN has to be an array of strings in AWS::AutoScaling::AutoScalingGroup NotificationConfiguration

### ISSUE THREAD

**Issue by ivorobioff** [aws-cloudformation/cfn-lint#2929]
### CloudFormation Lint Version

0.83.0

### What operating system are you using?

ubuntu

### Describe the bug

Even though the official documentation tells that TopicARM has to be an array of string the us-east-1.json specifies that it has to be string. 

Official Documentation https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-autoscaling-autoscalinggroup-notificationconfiguration.html#cfn-autoscaling-autoscalinggroup-notificationconfiguration-topicarn

![Screenshot_25](https://github.com/aws-cloudformation/cfn-lint/assets/563937/b4dc14c4-b738-4386-93a4-b2992a45b7db)

### Expected behavior

after running cfn-lint template.yaml no error has to be with the following configuration

![Untitled](https://github.com/aws-cloudformation/cfn-lint/assets/563937/34d02f78-5a49-4440-b212-782b50addb51)

### Reproduction template

unfortunately cannot provide one

**Comment by kddejong** [comment]
Yea this is a weird scenario.  It accepts both as long as the list is just one.  #2914

This will be fixed in v1 as we be able to support multiple types. At this time the CloudFormation specs we rely on only support one type.  This type was originally a string so that is why we are favoring that type over the list.
