### ISSUE TITLE
Is Valid latest release v1.3.0?

### ISSUE THREAD

**Issue by o-ga09** [aws-cloudformation/cfn-lint#3330]
**cfn-lint Version** v1.3.0

You can use `cfn-lint --version` to check the `cfn-lint` version on your system

**Provide additional details e.g. code snippets. _Be sure to remove any sensitive data._**

Is v1.3.0 the latest release for issues in cfn-lint, without pre-release?

I'm getting pip with no version specified to fail.

**Comment by tanya-ok** [comment]
There were problems with `1.3.0` too.
For now, I temporarily set the version to `0.87.7`:
`pip install cfn-lint==0.87.7`

**Comment by egut** [comment]
@tanya-ok I did the same in our CI/CD.

**Comment by r-heimann** [comment]
For anyone wondering, v1 is now GA: https://aws.amazon.com/blogs/devops/aws-cloudformation-linter-v1/

**Comment by o-ga09** [comment]
@r-heimann 
Thanks you!!!
I see. v1 is released now GA

**Comment by QuinnyPig** [comment]
Original cfn-lint to cfn-lint v1 has some breaking changes. What in the wide world of sports is going on with this insane versioning scheme?

**Comment by kddejong** [comment]
Sorry for the weird jump to 1.3 as I worked to rewrite cfn-lint from [specs](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/cfn-resource-specification.html) to [schemas](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/resource-type-schemas.html) I went through a few iterations of the logic. During testing (my own and customer feedback) I was evaluating the results and how to better scale going forward so I would do a rewrite of a portion of the solution and bump the version. We did [pre-releases](https://packaging.python.org/en/latest/specifications/version-specifiers/#pre-releases) into [pypi](https://pypi.org/project/cfn-lint/#history) (now mostly removed) and GitHub releases (still exist) but unless you are providing the correct parameters (or watching our different communication channels) you wouldn't have seen them or tested them. 

I would suggest using `pip install "cfn-lint<1"` instead of `pip install cfn-lint==0.87.7` as we will continue to update the v0 version with fixes and new versions of the specs as they are released (deprecation date TBD).  Please submit any issues you may find as I'm working quickly to resolve them. If we were integrating into cfn-lint either with another python package or using custom rules we can have a discussion about how to modify your rules to work with the schemas and the deprecated code.

Since we only had one major version upgrade in the 6 years of cfn-lint this next question may not arise a lot. My goal has always been to make your life easier when working with CloudFormation. For future knowledge and to improve this process going forward please let me know what I could have done differently.
